import nodemailer from 'nodemailer'
import { parsePaymentRequest } from 'ln-service'
import sanitizeHtml from 'sanitize-html'
import { emailAddress, gmailSettings, MAILTRAP } from './utilities'

export default async (req, res) => {
  let transport
  if (process.env.NODE_ENV === 'development') {
    transport = nodemailer.createTransport({
      host: "smtp.mailtrap.io",
      port: 2525,
      auth: {
        user: MAILTRAP.USER, //generated by Mailtrap
        pass: MAILTRAP.PASS //generated by Mailtrap
      },
      debug: true, // show debug output
      logger: true // log information in console
    });
  } else {
    transport = nodemailer.createTransport(gmailSettings)
  }

  try {
    await transport.verify()
  } catch (e) {
    console.error('Problem verifying smtp transport:', e)
    res.status(500)
    return res.end('Problem verifying smtp server')
  }

  const { subject, invoice, lsat, preimage, text, name, email } = req.body
  const request = parsePaymentRequest({ request: invoice })

  const mailOptions = {
      from: `"${name}" <${email}>`,
      replyTo: `"${name}" <${email}>`,
      to: emailAddress,
      subject: `[${request.tokens} Sats4Chats]: ${subject}`,
      text: text, 
      html: sanitizeHtml(text)
  }

  try {
    const info = await transport.sendMail(mailOptions)
    console.log('email successfully sent:', info.messageId)
  } catch (e) {
    console.error('Problem sending email:', e.message)
    res.status(500)
    return res.end('Problem sending email')
  }
  return res.end(JSON.stringify({ success: true }))
}